# -*- coding: utf-8 -*-
"""boystreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAptJj3SowVNVSJSA2GR3AvkUnwXG6NO
"""

!pip install streamlit

import streamlit as st

st.title('Meu Aplicativo Streamlit')
st.write('Este é um exemplo básico de um aplicativo Streamlit.')

# Salvar o código em um arquivo chamado app.py
with open('app.py', 'w') as f:
    f.write("""
# Código que você deseja salvar no arquivo app.py
""")

"""# Nova seção"""